### ISSUE TITLE
[bug] not all channels are displayed

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/integration_slack#8]
it would be probably helpful to describe which permissions are necessary.
As the channels are neither sorted nor searchable, I can not determine wich channels are missing.
I am sure that not all public channels are listed, nor my private ones.
May be this is also a Slack app configuration issue.

Slack-NC App can:
 View information about a user’s identity, granted by 1 team member
 View basic information about public channels in a workspace, granted by 1 team member
 View basic information about a user’s private channels, granted by 1 team member
 View basic information about a user’s direct messages, granted by 1 team member
 View basic information about a user’s group direct messages, granted by 1 team member
 View people in a workspace, granted by 1 team member
 Send messages on a user’s behalf, granted by 1 team member
 Upload, edit, and delete files on a user’s behalf, granted by 1 team member

**Comment by kyteinsky** [comment]
Hi, all the permissions are required for different parts of the app to function.

> View information about a user’s identity, granted by 1 team member

Used to display the profile picture and the user ID in 'Connected Accounts' section of user settings

> View basic information about public channels in a workspace, granted by 1 team member
> View basic information about a user’s private channels, granted by 1 team member
> View basic information about a user’s direct messages, granted by 1 team member
> View basic information about a user’s group direct messages, granted by 1 team member

For listing all the conversations, their icons and other related info

> View people in a workspace, granted by 1 team member

not sure where this comes from

> Send messages on a user’s behalf, granted by 1 team member
> Upload, edit, and delete files on a user’s behalf, granted by 1 team member

To send messages and files

The complete list of permissions this app requests: https://github.com/nextcloud/integration_slack/blob/main/src/utils.js#L27

I think with all the given permissions for conversations, it should list all of them. Can you provide examples of conversations/conversation types that are missing from the list?

**Comment by ferdiga** [comment]
Hi
After update to 28.0.3 and slack integration 1.1 
solved:
- the list of channels is sorted
- the list is searchable

open:
- still not all (public) channels are displayed

**Comment by kyteinsky** [comment]
> still not all (public) channels are displayed

would you mind posting a screenshot or something similar? It shows the complete list (private + public) for me.

**Comment by ferdiga** [comment]
Hi, it's obviously difficult to show channels which are not shown ;-)

in NC i type "terrain_hm" and it returns only 2 of the many channels
[20240503.170305.Files.pdf](https://github.com/nextcloud/integration_slack/files/15201727/20240503.170305.Files.pdf)

**Comment by kyteinsky** [comment]
Hello, see if the new release fixes this issue for you. I got no idea why some channels are not shown.

**Comment by adm-romanb** [comment]
> Hello, see if the new release fixes this issue for you. Otherwise I got no idea why some channels are not shown.

Still have this issue with 2.0 version. It shows only 20 channels (including channels I'm not a member of).
I'm a member of a big amount of channels so may be big list of channels cause some issue?

**Comment by ferdiga** [comment]
here it shows "ONLY" 100 channels , sorted alphabetical now and string selection works (inside the set of 100).

my guess is, that it shows the first 100 created (by date) which probably corresponds to the first 100 ids of the records.

**Comment by kyteinsky** [comment]
Thank you @adm-romanb and @ferdiga for your very useful observations!

@adm-romanb The endpoint for list of channels now fetches only channels the calling user is part of. You might an admin and have seen conversations other users are part of in the list. I'm not sure about the only 20 channels issue, how many should be there? See if the new release will fix it or create a new issue. Also, set the `'loglevel' => 0,` in the config/config.php file to see how many conversations are received from Slack side.

@ferdiga Yes, that is exactly what happened. I think at the time I must have assumed people won't have more than 100 conversations and the "limit" option was forgotten. Now it will fetch all the conversations there are, in 1000 conversation chunks.

**Comment by adm-romanb** [comment]
With version 2.0.1 channels listing is broken.
At first it was trying to get channels for a long time. Then it instantly shows an error "Failed to load Slack channels"
Logs are attached.[nextcloud_slack.log](https://github.com/user-attachments/files/17802572/nextcloud_slack.log)
> I'm not sure about the only 20 channels issue, how many should be there?
At least 60 public channels and 65 private ones.

**Comment by kyteinsky** [comment]
There are no errors reported in the logs. Do the browser console logs have something? `(Ctrl + Shift + i)`

**Comment by KMarkOne** [comment]
![Image](https://github.com/user-attachments/assets/228513d1-4582-4350-8e82-c09ba8f85ce8)

Hi, channel listing does not work at all.

**Comment by kyteinsky** [comment]
hi, can you post the server logs (tail -n50 data/nextcloud.log in the server) and the browser logs (Ctrl + Shift + i)?
After clicking on the refresh icon above the channel list.

**Comment by KMarkOne** [comment]
> hi, can you post the server logs (tail -n50 data/nextcloud.log in the server) and the browser logs (Ctrl + Shift + i)? After clicking on the refresh icon above the channel list.

Currently I send only the browser logs. Hope it helps.

`SendFilesModal.vue:387 TypeError: Cannot read properties of null (reading 'localeCompare')
    at SendFilesModal.vue:381:1
    at Array.sort (<anonymous>)
    at Array.<anonymous> (vue.runtime.esm.js:777:31)
    at SendFilesModal.vue:381:1
(anonymous) @ SendFilesModal.vue:387
Promise.catch
updateChannels @ SendFilesModal.vue:385
ye @ filesplugin.js:54
be @ filesplugin.js:95
exec @ filesplugin.js:75
onActionClick @ FileEntryActions.vue:161
click @ FileEntryActions.vue:4
hn @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
hn @ vue.runtime.esm.js:3033
e.$emit @ vue.runtime.esm.js:3732
onClick @ actionText-fFcUPi2g.mjs:77
handleClick @ NcActionButton.mjs:131
hn @ vue.runtime.esm.js:3033
n @ vue.runtime.esm.js:1832
Yr.i._wrapper @ vue.runtime.esm.js:7500`

**Comment by kyteinsky** [comment]
That should hopefully fix it now.

**Comment by ferdiga** [comment]
V 2.0.2 
Slack integration worked (Admin and Personal = Connected)

Trying to share: Failed to Load Slack channels 

I am on a hosted site -so I do not see any log files.

I have deleted the app and reinstalled everything afterwards.

**Comment by ferdiga** [comment]
Hetzner (service provider)  says the ydo not provide logging ....

**Comment by kyteinsky** [comment]
We'll see on Monday if something can be done about it.

**Comment by kyteinsky** [comment]
Are you sure the logging menu is not in the admin settings in the left sidebar? It should be included in all installations.
You can also go to `https://<your-domain>/index.php/settings/admin/logging` to access it.

If really not then we can try a different way. Are you familiar with the command line, docker stuff?

See pic for logging in admin settings: 

![](https://github.com/user-attachments/assets/d61a0a21-5975-4973-843a-0b40e4dd396f)

**Comment by ferdiga** [comment]
I installed the module on a NC 30 instance hosted on our internal server, and all slack channels are displayed and selectable.


The problem occurs on a NC 29 hosted by Hetzner.
I'll wait until they update to NC 30.

**Comment by kyteinsky** [comment]
Ah that clears things up. Verified again the app works with NC 29 so it should be Hetzner's issue like rate-limiting on their IP by Slack.
Closing this issue, let me know if this pops up again.
